### ISSUE TITLE
ability to specify arch

### ISSUE THREAD

**Issue by jhigdon** [marler8997/zigup#60]
Hello, 

Is there a way to specify arch ? 

Current issue: 
$ zigup master
retrieves zig-macos-x86_64 but I would like zig-macos-aarch64

Thanks!

**Comment by marler8997** [comment]
It should pull the arch from your current host architecture (i.e. https://github.com/marler8997/zigup/blob/9f8c5f98cd2052370ad676ebf287eb25106f2be8/zigup.zig#L17).  Are you on arm machine and it's pulling down x86, or were you trying to pull down the arm build on an x86 machine?

**Comment by jhigdon** [comment]
I am on a m1 mac that is pulling down x86, the terminal reports arm64 when running "arch" command. but the zigup is zigup: Mach-O 64-bit executable x86_64. In this scenario I would actually like it to pull down aarch64 version. I don't think "builtin.cpu.arch" pulls in the native cpu arch in this case or it's being confused because the x86 zigup is running in rosetta maybe?

**Comment by jhigdon** [comment]
I downloaded one from releases;  yep 'builtin.cpu.arch' is reporting x86_64 because the program is running in rosetta etc, a update to the archives would be awesome!

**Comment by zenspider** [comment]
1. download the zigup binary for x86, fails to install zig 0.10 because of some download issue
2. download zig 0.10 binary, try to build zigup... fails on:

```
/Users/ryan/Work/git/marler8997/zigup/dep/ziget/ziget.zig:8:6: error: empty test name must be omitted
test "" {
     ^~
```

there's a real bootstrapping issue here. Either arch needs to be an option or #10 needs to be worked out. SOME way to start from scratch or from latest stable release. The current code doesn't work with 0.9 OR 0.10 and that's more friction than I know how to deal with.

**Comment by xEgoist** [comment]
I can confirm that this is related to downloading the x86_64 binaries from the release page. 
Rosetta would still be able to run zigup. However, because the architecture of the CPU is reported as x86 from rosetta. zigup will download the x86_64.

One way to solve this issue is by tweaking the CI and creating the cross-compiled binaries for aarch64 for people to download. 
I attempted to do so in my fork: [Here are some sample artifacts](https://github.com/xEgoist/zigup/actions/runs/2908362130)

changes are also found [here](https://github.com/xEgoist/zigup/commit/545dc62c9ba9b21eedf866a7ea67ad5d20cb1edb#diff-3d245273938e713d302c0cc673152c88b677ac8d73d0edfe9c8780551a93da15)

The only caveat of doing it completely from CI is that it requires building without testing for anything other than x86_64 due to what github action provides. 

I am unsure whether this change is plausible, but I can tidy the CI a bit and make a pull request if needed.

**Comment by marler8997** [comment]
@xEgoist your change looks plausible.  PR welcome.

**Comment by marler8997** [comment]
The latest release includes aarch64 binaries for macos: https://github.com/marler8997/zigup/releases/tag/v2022_08_25
