### ISSUE TITLE
zigup does not compile with latest master (`0.11.0-dev.1782+b52be973d`)

### ISSUE THREAD

**Issue by DivergentClouds** [marler8997/zigup#81]
I get the error
```
/home/clouds/Downloads/zigup/GitRepoStep.zig:60:14: error: expected type '[]const u8', found 'Build.Cache.Directory'
            b.build_root,
            ~^~~~~~~~~~~
/home/clouds/zig/0.11.0-dev.1782+b52be973d/files/lib/std/Build/Cache.zig:5:23: note: struct declared here
pub const Directory = struct {
                      ^~~~~~
referenced by:
    buildOrFail: /home/clouds/Downloads/zigup/build.zig:22:35
    buildNoreturn: /home/clouds/Downloads/zigup/build.zig:14:17
    remaining reference traces hidden; use '-freference-trace' to see all reference traces

/home/clouds/Downloads/zigup/build.zig:52:43: error: expected type '[]const u8', found 'Build.Cache.Directory'
    run_step.addArg(self.pathFromRoot(self.cache_root));
                                      ~~~~^~~~~~~~~~~
/home/clouds/zig/0.11.0-dev.1782+b52be973d/files/lib/std/Build/Cache.zig:5:23: note: struct declared here
pub const Directory = struct {
                      ^~~~~~
/home/clouds/zig/0.11.0-dev.1782+b52be973d/files/lib/std/Build.zig:1344:35: note: parameter type declared here
pub fn pathFromRoot(b: *Build, p: []const u8) []u8 {
                                  ^~~~~~~~~~
/home/clouds/Downloads/zigup/GitRepoStep.zig:186:24: error: expected type '?[]const u8', found 'Build.Cache.Directory'
    child.cwd = builder.build_root;
                ~~~~~~~^~~~~~~~~~~
/home/clouds/zig/0.11.0-dev.1782+b52be973d/files/lib/std/Build/Cache.zig:5:23: note: struct declared here
pub const Directory = struct {
```

when compiling on version `0.11.0-dev.1782+b52be973d`

**Comment by resolritter** [comment]
Try using `0.11.0-dev.1507+6f13a725a`, which is what CI currently uses: https://github.com/marler8997/zigup/blob/a16b61e74e47b3dbd7be45ba1dcdf8a1d259a8c5/.github/workflows/artifact.yml#L15
